Added code for language issue
fossasia/publiccode.asia pull request #155
Opened 2018-09-08 20:56 UTC by pranav1698

Added code corresponding to issue #146

2018-09-12 00:47 UTC, praveenojha33 commented
@pranav1698 Please provide a demo link.

2018-09-12 06:35 UTC, yohanym95 approved these changes

2018-09-12 06:37 UTC, pranav1698 commented
hey @praveenojha33,
Actually I am new to open source development so sorry but I don't know how to create a demo link 
If you could help me for the same, I have tested my changes in my localhost

2018-09-12 06:52 UTC, pranav1698 commented
You can check it now,
https://pranav1698.fwd.wf

2018-09-12 08:44 UTC, yohanym95 commented
provide a link, not a language.

2018-09-12 13:57 UTC, praveenojha33 commented
@pranav1698 Please use surge or heroku. Please do a little search on internet for common queries.

2018-09-12 17:00 UTC, pranav1698 commented
http://c35152c4.ngrok.io/ this is the link for the demo 
I have used local tunneling for the demo link;

2018-09-13 15:53 UTC, abishekvashok commented
Link returns 404

2018-09-14 04:58 UTC, pranav1698 commented
Hey @abishekvashok;
Actually the site was on local tunelling and I could'nt open my workstation yesterday;
You can check it now, the link is: http://c674b602.ngrok.io/

2018-09-14 16:44 UTC, pranav1698 commented
Were you not able to check in the above link

On Fri, Sep 14, 2018, 21:53 Abishek V Ashok <notifications@github.com>
wrote:

> Maybe you could build it, see build section in readme, and then deploy it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/publiccode.asia/pull/155#issuecomment-421411127>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AhJO2U7CfEzvbSloZPuB1IJDYTtIbFHiks5ua9fygaJpZM4WgB7g>
> .
>

2018-09-17 07:35 UTC, pranav1698 commented
No the instructions clearly indicate that you can view your changes on your computer only;
If you could help me when you are free; then I will host the demo link at that time; as when I used surge and heroku the css was not loading
At this moment the demo link is: http://d9e3a17b.ngrok.io/

2018-09-20 17:56 UTC, pranav1698 commented
No the instructions clearly indicate that you can view your changes on your computer only;
If you could help me when you are free; then I will host the demo link at that time; as when I used surge and heroku the css was not loading
At this moment the demo link is: http://b7a20d99.ngrok.io/

2018-09-21 05:19 UTC, abishekvashok commented
If you could provide screenshots it will be okay as well

2018-09-21 05:39 UTC, pranav1698 commented
Sure,  abhishek on it

On Fri, Sep 21, 2018, 10:49 Abishek V Ashok <notifications@github.com>
wrote:

> If you could provide screenshots it will be okay as well
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/publiccode.asia/pull/155#issuecomment-423416328>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AhJO2cYElSegJ8r0ZeBY0Yz9Ex07yOOWks5udHbpgaJpZM4WgB7g>
> .
>

2018-09-21 08:29 UTC, abishekvashok commented
Maybe along with it provide a gif or video

2018-09-21 09:06 UTC, pranav1698 commented
Hey @abishekvashok, 
The gif for the language issue
![publiccode](https://user-images.githubusercontent.com/34754265/45871623-8ef0c080-bdab-11e8-8d80-cecf00ca1c0f.gif)

2018-09-21 11:12 UTC, abishekvashok approved these changes

2018-09-21 18:26 UTC, praveenojha33 approved these changes

2018-09-21 18:32 UTC, samagragupta requested changes

2018-09-23 20:52 UTC, pranav1698 commented on site/static/css/creative.css
> +}
Sorry for the delay

2018-11-03 01:18 UTC, NaviRocker approved these changes
LGTM

2018-11-03 04:52 UTC, sarnava1 approved these changes

2018-11-19 14:48 UTC, merged

2020-07-05 08:45 UTC, akash-arelli commented
I would like to work  this issue. The dropdown list shoes languages in short form which is confusing. I would like to add original languages name in original language.