Added a background color to the dropdown
fossasia/publiccode.asia pull request #183
Opened 2020-02-27 23:59 UTC by adebayoileri

Helps for good readability of nav links  for mobile phones

2020-02-28 13:07 UTC, Peterbamidele approved these changes

2020-03-03 10:37 UTC, abishekvashok requested changes
Please dont use custom styles

2020-03-03 18:07 UTC, adebayoileri commented
It’s inline css, guess it won’t affect other elements

2020-03-03 18:07 UTC, adebayoileri commented
Will fix

2020-03-16 12:45 UTC, closed without merging